import { iUser } from "@/models/data-models";

export const users = [
  {
    id: 17,
    username: "demo1",
    firstname: "Rick",
    lastname: "James",
    city: null,
    phone: null,
    profile_id: 2,
    balance: "0.00",
    loan_balance: null,
    expiration: "2021-10-08 13:06:00",
    last_online: null,
    parent_id: 3,
    email: null,
    static_ip: null,
    enabled: 1,
    company: null,
    notes: null,
    simultaneous_sessions: 1,
    address: null,
    contract_id: null,
    created_at: "2021-09-08 13:05:51",
    national_id: null,
    mikrotik_ipv6_prefix: null,
    group_id: null,
    gps_lat: null,
    gps_lng: null,
    street: null,
    n_row: 1,
    remaining_days: 0,
    status: {
      status: false,
      traffic: true,
      expiration: false,
      uptime: true,
    },
    online_status: 0,
    parent_username: "Manager_2",
    profile_details: {
      id: 2,
      name: "Slow",
      type: 0,
    },
    daily_traffic_details: null,
    group_details: null,
  },
  {
    id: 8,
    username: "demo2",
    firstname: "Miller",
    lastname: "Pascal",
    city: null,
    phone: null,
    profile_id: 1,
    balance: "-100010141.00",
    loan_balance: "-141.00",
    expiration: "2022-01-22 00:45:31",
    last_online: null,
    parent_id: 3,
    email: null,
    static_ip: null,
    enabled: 1,
    company: null,
    notes: null,
    simultaneous_sessions: 1,
    address: null,
    contract_id: null,
    created_at: "2021-07-26 13:33:04",
    national_id: null,
    mikrotik_ipv6_prefix: null,
    group_id: null,
    gps_lat: "34.895158",
    gps_lng: "21.686261",
    street: null,
    n_row: 2,
    remaining_days: 0,
    status: {
      status: false,
      traffic: true,
      expiration: false,
      uptime: true,
    },
    online_status: 0,
    parent_username: "Manager_2",
    profile_details: {
      id: 1,
      name: "default-2Mbit-1Month",
      type: 0,
    },
    daily_traffic_details: null,
    group_details: null,
  },
  {
    id: 9,
    username: "demo3",
    firstname: "Tyson",
    lastname: "Edge",
    city: null,
    phone: null,
    profile_id: 3,
    balance: "0.00",
    loan_balance: "-100.00",
    expiration: "2021-09-22 12:33:24",
    last_online: null,
    parent_id: 1,
    email: null,
    static_ip: null,
    enabled: 1,
    company: null,
    notes: null,
    simultaneous_sessions: 1,
    address: null,
    contract_id: null,
    created_at: "2021-07-26 13:34:17",
    national_id: null,
    mikrotik_ipv6_prefix: null,
    group_id: null,
    gps_lat: null,
    gps_lng: null,
    street: null,
    n_row: 3,
    remaining_days: 0,
    status: {
      status: false,
      traffic: true,
      expiration: false,
      uptime: true,
    },
    online_status: 0,
    parent_username: "admin",
    profile_details: {
      id: 3,
      name: "Standard",
      type: 0,
    },
    daily_traffic_details: null,
    group_details: null,
  },
  {
    id: 10,
    username: "demo4",
    firstname: "Gabriel",
    lastname: "Andrews",
    city: null,
    phone: null,
    profile_id: 1,
    balance: "0.00",
    loan_balance: "-67.00",
    expiration: "2022-10-06 01:39:34",
    last_online: null,
    parent_id: 5,
    email: null,
    static_ip: null,
    enabled: 1,
    company: null,
    notes: null,
    simultaneous_sessions: 1,
    address: null,
    contract_id: null,
    created_at: "2021-07-26 13:36:07",
    national_id: null,
    mikrotik_ipv6_prefix: null,
    group_id: null,
    gps_lat: null,
    gps_lng: null,
    street: null,
    n_row: 4,
    remaining_days: 0,
    status: {
      status: false,
      traffic: true,
      expiration: false,
      uptime: true,
    },
    online_status: 0,
    parent_username: "Manager_4",
    profile_details: {
      id: 1,
      name: "default-2Mbit-1Month",
      type: 0,
    },
    daily_traffic_details: null,
    group_details: null,
  },
] as iUser[];
